-- vim.api.nvim_create_autocmd("FileType", {
--   pattern = { "python" },
--   callback = function()
--     local client = vim.lsp.start_client {
--       name = "lsproxy",
--       cmd = { "/Users/richard/proj/lsproxy/target/debug/lsproxy" },
--       on_attach = require 'functions.lsp'.on_attach,
--       cmd_env = { RUST_LOG = "trace" }
--     }
--
--     if not client then
--       vim.notify("Something was wrong with lsproxy")
--     end
--     vim.lsp.buf_attach_client(0, client)
--   end
-- })
