-- Work around a cargo/rust-analyzer incompatibility:
-- the installed cargo (1.95.0-nightly) does NOT accept `--lockfile-path` on
-- `cargo metadata`, but rust-analyzer passes it unconditionally. When
-- metadata-with-deps fails, RA silently falls back to `--no-deps` -> no resolved
-- dependency graph -> degraded hover/goto across crate boundaries (and dead
-- `#[cfg(feature=...)]` blocks). RA runs `$CARGO_HOME/bin/cargo` for metadata
-- (ignoring $CARGO and PATH), so we point CARGO_HOME at a shim home whose
-- bin/cargo strips `--lockfile-path` and forwards to the real cargo. registry/
-- git/config are symlinked to the real ~/.cargo so nothing re-downloads.
-- Remove this once cargo accepts the flag (or RA stops sending it).
local function ensure_cargo_shim()
  local home = vim.env.HOME
  local shim = vim.fs.joinpath(vim.fn.stdpath("data"), "ra-cargo-home")
  vim.fn.mkdir(vim.fs.joinpath(shim, "bin"), "p")

  -- Mirror the real cargo home so behaviour is identical apart from bin/cargo.
  for _, name in ipairs({ "registry", "git", "config.toml", "credentials.toml" }) do
    local src, dst = vim.fs.joinpath(home, ".cargo", name), vim.fs.joinpath(shim, name)
    if vim.uv.fs_stat(src) and not vim.uv.fs_lstat(dst) then
      vim.uv.fs_symlink(src, dst)
    end
  end

  local cargo = vim.fs.joinpath(shim, "bin", "cargo")
  local script = table.concat({
    "#!/usr/bin/env bash",
    "# Generated by lsp/rust_analyzer.lua: strip `--lockfile-path` (unsupported",
    "# by this cargo's `metadata`) and forward to the real rustup cargo proxy.",
    "filtered=(); skip=0",
    'for a in "$@"; do',
    '  if [ "$skip" = 1 ]; then skip=0; continue; fi',
    "  case \"$a\" in --lockfile-path) skip=1; continue ;; --lockfile-path=*) continue ;; esac",
    '  filtered+=("$a")',
    "done",
    'exec "${HOME}/.cargo/bin/cargo" "${filtered[@]}"',
    "",
  }, "\n")
  -- Rewrite only when changed so we don't thrash the file on every load.
  local current = vim.uv.fs_stat(cargo) and table.concat(vim.fn.readfile(cargo), "\n") or ""
  if current ~= vim.trim(script) then
    vim.fn.writefile(vim.split(script, "\n"), cargo)
    vim.uv.fs_chmod(cargo, 493) -- 0755
  end
  return shim
end

local ok, cargo_home = pcall(ensure_cargo_shim)

return {
  cmd = { 'rust-analyzer' },
  cmd_env = ok and { CARGO_HOME = cargo_home } or nil,
  filetypes = { 'rust' },
  single_file_support = true,
  root_markers = {
    "Cargo.toml",
    ".git"
  },
  capabilities = {
    experimental = {
      serverStatusNotification = true,
    },
  },
  settings = {
    ["rust-analyzer"] = {
      diagnostics = {
        disabled = { "inactive-code" },
      },
      cargo = {
        features = "all",
        targetDir = "target/debug",
      },
      checkOnSave = {
        enable = true,
      },
      check = {
        command = "clippy",
      },
      files = {
        exclude = {
          "**/.git/**",
          "**/target/**",
          "**/node_modules/**",
          "**/dist/**",
          "**/out/**",
        }
      },
      completion = {
        postfix = {
          enable = false,
        },
      },
    },
  },
  before_init = function(init_params, config)
    if config.settings and config.settings['rust-analyzer'] then
      init_params.initializationOptions = config.settings['rust-analyzer']
    end
  end,
}
